describe("RC3", () => {
  it("tests RC3", () => {
    cy.viewport(1130, 792);
    cy.visit("http://localhost:5173/collection");
    cy.get("a:nth-of-type(7) img").click();
    cy.get("button:nth-of-type(2)").click();
    cy.get("div:nth-of-type(2) > button").click();
    cy.get("button > svg").click();
    cy.get("div.flex > div.flex > a > img").click();
    cy.get("button").click();
    cy.get("div:nth-of-type(2) > input:nth-of-type(1)").click();
    cy.get("div:nth-of-type(2) > input:nth-of-type(1)").type("u");
    cy.get("div:nth-of-type(2) > input:nth-of-type(1)").type("U");
    cy.get("div:nth-of-type(2) > input:nth-of-type(1)").type("User");
    cy.get("div:nth-of-type(2) > input:nth-of-type(2)").type("2");
    cy.get("input[type='email']").type("4568");
    cy.get("input[type='email']").type("4568 R");
    cy.get("input[type='email']").type("4568 Rashford");
    cy.get("input[type='email']").dblclick();
    cy.get("input[type='email']").type("4568");
    cy.get("form > div.flex > input[type='text']").click();
    cy.get("form > div.flex > input[type='text']").type("Rashford");
    cy.get("div:nth-of-type(3) > input:nth-of-type(1)").click();
    cy.get("div:nth-of-type(3) > input:nth-of-type(1)").type("Toronto");
    cy.get("div:nth-of-type(3) > input:nth-of-type(2)").type("O");
    cy.get("div:nth-of-type(3) > input:nth-of-type(2)").type("Ontario");
    cy.get("div:nth-of-type(4) > input:nth-of-type(1)").type("M");
    cy.get("div:nth-of-type(4) > input:nth-of-type(1)").type("M9Z");
    cy.get("div:nth-of-type(4) > input:nth-of-type(1)").type("M9Z 07");
    cy.get("div:nth-of-type(4) > input:nth-of-type(1)").type("M9Z 07A");
    cy.get("div:nth-of-type(4) > input:nth-of-type(2)").click();
    cy.get("div:nth-of-type(4) > input:nth-of-type(2)").type("C");
    cy.get("div:nth-of-type(4) > input:nth-of-type(2)").type("Canada");
    cy.get("input[type='number']").click();
    cy.get("input[type='number']").type("437605241");
    cy.get("div:nth-of-type(3) > p.min-w-3\\.5").click();
    cy.get("button").click();
    cy.get("input[type='email']").click();
    cy.get("input[type='email']").click();
    cy.get("input[type='email']").dblclick();
    cy.get("input[type='email']").type("");
    cy.type("{backspace}");
    cy.get("input[type='email']").type("U");
    cy.get("input[type='email']").type("User2");
    cy.get("input[type='email']").type("User2@");
    cy.get("input[type='email']").type("User2@mail.com");
    cy.get("button").click();
    cy.get("#root > div").click();
  });
});
//# recorderSourceMap=BCBDBEBFBGBHBIBJBKBLALALBMAMAMBNANANBOAOAOBPAPAPBQAQAQBRARARBSASASBTBUBVBWBXAXAXBYAYAYAYAYBZAZAZAZBaAaAaAaAaBbAbAbBcAcAcAcBdAdAdBeAeAeAeBfAfAfBgBAgBAgBBhBBiBBjBBkBBlBBmBBnBBoBBpBBqBAqBAqBAqBBrBArBArBBsBAsBAsBAsBAsBAsBAsBBtBAtBBuBBvBB
