describe("RC5", () => {
  it("tests RC5", () => {
    cy.viewport(1130, 792);
    cy.visit("http://localhost:5173/cart");
    cy.get("button").click();
    cy.get("div:nth-of-type(2) > input:nth-of-type(1)").click();
    cy.get("div:nth-of-type(2) > input:nth-of-type(1)").type("U");
    cy.get("div:nth-of-type(2) > input:nth-of-type(1)").type("User");
    cy.get("div:nth-of-type(2) > input:nth-of-type(2)").type("1");
    cy.get("input[type='email']").click();
    cy.get("input[type='email']").type("77 mabelle");
    cy.get("form > div.flex > input[type='text']").click();
    cy.get("form > div.flex > input[type='text']").type("A");
    cy.get("form > div.flex > input[type='text']").type("Apt14");
    cy.get("div:nth-of-type(3) > input:nth-of-type(1)").click();
    cy.get("div:nth-of-type(3) > input:nth-of-type(1)").type("Toronto");
    cy.get("div:nth-of-type(3) > input:nth-of-type(2)").type("O");
    cy.get("div:nth-of-type(3) > input:nth-of-type(2)").type("On");
    cy.get("div:nth-of-type(3) > input:nth-of-type(2)").type("Ontario");
    cy.get("div:nth-of-type(4) > input:nth-of-type(1)").type("M");
    cy.get("div:nth-of-type(4) > input:nth-of-type(1)").type("M9a016");
    cy.get("div:nth-of-type(4) > input:nth-of-type(2)").click();
    cy.get("div:nth-of-type(4) > input:nth-of-type(2)").type("X");
    cy.get("div:nth-of-type(4) > input:nth-of-type(2)").type("C");
    cy.get("div:nth-of-type(4) > input:nth-of-type(2)").type("Canada");
    cy.get("input[type='number']").click();
    cy.get("input[type='number']").type("4376050405");
    cy.get("div.mt-8 div.flex p.text-gray-500").click();
    cy.get("div.mt-12 > div.flex > div:nth-of-type(3)").click();
    cy.get("div:nth-of-type(3) > p.min-w-3\\.5").click();
    cy.get("div.mt-12 > div.flex > div:nth-of-type(3)").click();
    cy.get("div.mt-12 div:nth-of-type(2) > p").click();
    cy.get("div.mt-12 > div.flex > div:nth-of-type(3)").click();
    cy.get("button").click();
    cy.get("input[type='email']").click();
    cy.get("input[type='email']").type("77mabelle");
    cy.get("input[type='email']").dblclick();
    cy.get("input[type='email']").click();
    cy.get("input[type='email']").type("U");
    cy.get("input[type='email']").type("User1@");
    cy.get("input[type='email']").type("User1@mail.com");
    cy.get("button").click();
    cy.get("div:nth-of-type(2) > div:nth-of-type(1) button").click();
    cy.get("div:nth-of-type(2) > div:nth-of-type(1) button").click();
    cy.get("div:nth-of-type(2) > div:nth-of-type(2) button").click();
    cy.get("div:nth-of-type(2) > div:nth-of-type(1) button").click();
  });
});
//# recorderSourceMap=BCBDBEBFBGBHAHAHBIAIAIBJBKBLBMBNANANANBOBPAPAPBQAQAQAQAQBRARARBSASBTATATATATBUAUAUBVBWAWAWBXAXAXBYAYAYAYBZBaBbBcBdBeBfBgBBhBBiBBjBBkBBlBBmBAmBAmBBnBAnBAnBAnBBoBAoBBpBBqBBrBBsBBtBB
